apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- nginx-deployment.yaml
- nginx-svc.yaml
commonLabels:
  app: myhomelab-app
commonAnnotations:
  channel: homelab
nameSuffix:
  -v0-1-0
namePrefix:
  tobi-